# Generated by Django 5.2.12 on 2026-04-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0006_projectobject_geofence_polygon_and_more'),
        ('pricing', '0003_alter_pricelistitem_name'),
        ('users', '0004_remove_user_roles_user_role_delete_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('morning', 'Утренний (выдача)'), ('evening', 'Вечерний (возврат)')], max_length=16, verbose_name='Тип чек-листа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Заполнил')),
            ],
            options={
                'verbose_name': 'Чек-лист оборудования',
                'verbose_name_plural': 'Чек-листы оборудования',
                'db_table': 'workday_equipmentchecklist',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('status', models.CharField(choices=[('ok', 'В наличии'), ('missing', 'Отсутствует'), ('damaged', 'Повреждён')], default='ok', max_length=16, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, upload_to='workday/equipment/%Y/%m/%d/', verbose_name='Фото')),
                ('qr_code', models.CharField(blank=True, max_length=255, verbose_name='QR-код')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workday.equipmentchecklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Позиция чек-листа',
                'verbose_name_plural': 'Позиции чек-листа',
                'db_table': 'workday_equipmentcheckitem',
            },
        ),
        migrations.CreateModel(
            name='ObjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(verbose_name='Время прибытия')),
                ('arrived_photo', models.ImageField(upload_to='workday/arrive/%Y/%m/%d/', verbose_name='Фото прибытия')),
                ('arrived_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS широта (прибытие)')),
                ('arrived_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS долгота (прибытие)')),
                ('departed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время убытия')),
                ('departed_photo', models.ImageField(blank=True, upload_to='workday/depart/%Y/%m/%d/', verbose_name='Фото убытия')),
                ('departed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS широта (убытие)')),
                ('departed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS долгота (убытие)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='objects.projectobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Сессия на объекте',
                'verbose_name_plural': 'Сессии на объектах',
                'db_table': 'workday_objectsession',
                'ordering': ('arrived_at',),
            },
        ),
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Объём')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to='pricing.pricelistitem', verbose_name='Вид работы')),
                ('object_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to='workday.objectsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
                'db_table': 'workday_completedwork',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('clock_in_at', models.DateTimeField(verbose_name='Время начала смены')),
                ('clock_in_photo', models.ImageField(upload_to='workday/clock_in/%Y/%m/%d/', verbose_name='Фото начала смены')),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS широта (начало)')),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS долгота (начало)')),
                ('clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Время конца смены')),
                ('clock_out_photo', models.ImageField(blank=True, upload_to='workday/clock_out/%Y/%m/%d/', verbose_name='Фото конца смены')),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS широта (конец)')),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS долгота (конец)')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('approved', 'Принят'), ('rejected', 'Отклонён')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('pm_comment', models.TextField(blank=True, verbose_name='Комментарий РП')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приёмки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workdays', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='users.brigade', verbose_name='Бригада')),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays_as_foreman', to=settings.AUTH_USER_MODEL, verbose_name='Мастер (бригадир)')),
                ('workers_present', models.ManyToManyField(blank=True, related_name='workday_presences', to=settings.AUTH_USER_MODEL, verbose_name='Присутствующие работники')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'db_table': 'workday_workday',
                'ordering': ('-date', '-clock_in_at'),
            },
        ),
        migrations.AddField(
            model_name='objectsession',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workday.workday', verbose_name='Рабочий день'),
        ),
        migrations.AddField(
            model_name='equipmentchecklist',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checklists', to='workday.workday', verbose_name='Рабочий день'),
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='workday/work_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS долгота')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Время съёмки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('completed_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workday.completedwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работ',
                'db_table': 'workday_workphoto',
                'ordering': ('created_at',),
            },
        ),
    ]
