# Generated by Django 5.2.12 on 2026-03-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('users', '0004_remove_user_roles_user_role_delete_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectobject',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AddField(
            model_name='projectobject',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='attrs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. атрибуты'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='users.brigade', verbose_name='Прикреплённая бригада'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='customer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дэдлайн'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_objects', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.CreateModel(
            name='ObjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('doc_type', models.CharField(choices=[('rd', 'Рабочая документация (РД)'), ('project', 'Проект'), ('act', 'Акт'), ('scheme', 'Схема'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='objects/documents/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='objects.projectobject', verbose_name='Объект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ объекта',
                'verbose_name_plural': 'Документы объектов',
                'db_table': 'objects_objectdocument',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ObjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=128, verbose_name='Название стадии')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('project_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='objects.projectobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Стадия объекта',
                'verbose_name_plural': 'Стадии объектов',
                'db_table': 'objects_objectstage',
                'ordering': ('order',),
                'unique_together': {('project_object', 'order')},
            },
        ),
        migrations.AddField(
            model_name='projectobject',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='objects.objectstage', verbose_name='Текущая стадия'),
        ),
    ]
