# Generated by Django 5.2.12 on 2026-03-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_expand_projectobject'),
        ('users', '0004_remove_user_roles_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobject',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_objects', to='users.brigade', verbose_name='Прикреплённая бригада'),
        ),
    ]
