# Generated by Django 5.2.12 on 2026-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_stage_as_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
    ]
