# Generated by Django 5.2.12 on 2026-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_add_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='geofence_polygon',
            field=models.JSONField(blank=True, default=list, help_text='Массив координат [[lat, lng], ...] для определения границ объекта', verbose_name='Геозона (полигон)'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='presence_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Радиус в метрах для определения присутствия бригады на объекте', null=True, verbose_name='Радиус присутствия (м)'),
        ),
    ]
