# Generated by Django 5.1.7 on 2026-04-22 14:14

from django.db import migrations, models


def forwards_fill_statuses(apps, schema_editor):
    ProjectObject = apps.get_model("objects", "ProjectObject")

    decision_map = {
        "Анализ": "analysis",
        "Строим": "in_progress",
        "Отказ": "rejected",
        "Передан СП": "transferred_to_sp",
        "Архив анализ": "archive_analysis",
    }
    construction_map = {
        "Обследовать": "survey",
        "Выбрать ПО": "select_software",
        "Строить": "build",
        "Завершен": "completed",
        "Завершен (доделать)": "completed_todo",
        "Завершен оплачен": "completed_paid",
    }
    materials_map = {
        "Заказать": "order",
        "Заказаны": "ordered",
        "Пришли": "arrived",
        "СП": "sp",
    }
    pir_map = {
        "Разработать": "develop",
        "Согл. с РТК": "agreed_rtk",
        "Согл. со службами": "agreed_services",
        "Сдать ПИР": "submit_pir",
        "Завершен": "completed",
        "Не брали": "not_taken",
        "СП": "sp",
    }
    as_built_map = {
        "Назначить": "assign",
        "Разработка": "in_development",
        "Сдан МП": "submitted_mp",
        "Проверка РТК": "check_rtk",
        "Доработка ПП": "rework_pp",
        "Сдан ПП": "submitted_pp",
        "Не требуется": "not_required",
    }

    for obj in ProjectObject.objects.all().iterator():
        attrs = obj.attrs or {}

        decision_raw = attrs.get("decision_status") or attrs.get("status") or attrs.get("решение")
        construction_raw = attrs.get("construction_status") or attrs.get("status_construction") or attrs.get("статус стройки")
        materials_raw = attrs.get("materials_status") or attrs.get("status_materials") or attrs.get("статус материалы")
        pir_raw = attrs.get("pir_status") or attrs.get("status_pir") or attrs.get("статус пир")
        as_built_raw = attrs.get("as_built_status") or attrs.get("status_id") or attrs.get("статус ид")

        changed = False

        if not obj.decision_status and isinstance(decision_raw, str):
            mapped = decision_map.get(decision_raw.strip())
            if mapped:
                obj.decision_status = mapped
                changed = True
        if not obj.construction_status and isinstance(construction_raw, str):
            mapped = construction_map.get(construction_raw.strip())
            if mapped:
                obj.construction_status = mapped
                changed = True
        if not obj.materials_status and isinstance(materials_raw, str):
            mapped = materials_map.get(materials_raw.strip())
            if mapped:
                obj.materials_status = mapped
                changed = True
        if not obj.pir_status and isinstance(pir_raw, str):
            mapped = pir_map.get(pir_raw.strip())
            if mapped:
                obj.pir_status = mapped
                changed = True
        if not obj.as_built_status and isinstance(as_built_raw, str):
            mapped = as_built_map.get(as_built_raw.strip())
            if mapped:
                obj.as_built_status = mapped
                changed = True

        if changed:
            obj.save(
                update_fields=[
                    "decision_status",
                    "construction_status",
                    "materials_status",
                    "pir_status",
                    "as_built_status",
                    "updated_at",
                ]
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_projectobject_geofence_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='as_built_status',
            field=models.CharField(blank=True, choices=[('assign', 'Назначить'), ('in_development', 'Разработка'), ('submitted_mp', 'Сдан МП'), ('check_rtk', 'Проверка РТК'), ('rework_pp', 'Доработка ПП'), ('submitted_pp', 'Сдан ПП'), ('not_required', 'Не требуется')], db_index=True, max_length=32, verbose_name='Статус ИД'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('survey', 'Обследовать'), ('select_software', 'Выбрать ПО'), ('build', 'Строить'), ('completed', 'Завершен'), ('completed_todo', 'Завершен (доделать)'), ('completed_paid', 'Завершен оплачен')], db_index=True, max_length=32, verbose_name='Статус стройки'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='decision_status',
            field=models.CharField(blank=True, choices=[('analysis', 'Анализ'), ('in_progress', 'Строим'), ('rejected', 'Отказ'), ('transferred_to_sp', 'Передан СП'), ('archive_analysis', 'Архив анализ')], db_index=True, max_length=32, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='materials_status',
            field=models.CharField(blank=True, choices=[('order', 'Заказать'), ('ordered', 'Заказаны'), ('arrived', 'Пришли'), ('sp', 'СП')], db_index=True, max_length=32, verbose_name='Статус материалы'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='pir_status',
            field=models.CharField(blank=True, choices=[('develop', 'Разработать'), ('agreed_rtk', 'Согл. с РТК'), ('agreed_services', 'Согл. со службами'), ('submit_pir', 'Сдать ПИР'), ('completed', 'Завершен'), ('not_taken', 'Не брали'), ('sp', 'СП')], db_index=True, max_length=32, verbose_name='Статус ПИР'),
        ),
        migrations.RunPython(forwards_fill_statuses, noop_reverse),
    ]
