# Generated by Django 5.2.12 on 2026-03-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_brigade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_brigades', to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='brigades', to=settings.AUTH_USER_MODEL, verbose_name='Состав бригады'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название бригады'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('administrator', 'Администратор'), ('director', 'Директор'), ('project_manager', 'Руководитель проекта'), ('foreman', 'Мастер (бригадир)'), ('worker', 'Монтажник'), ('support_manager', 'Менеджер по сопровождению'), ('designer', 'Проектировщик'), ('customer', 'Заказчик'), ('accountant', 'Бухгалтер')], help_text='Системный код роли для проверки прав доступа.', max_length=64, unique=True, verbose_name='Код роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=True, help_text='Системные роли создаются автоматически и используются в RBAC.', verbose_name='Системная роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('dismissed', 'Уволен')], db_index=True, default='active', help_text='Текущий статус сотрудника в системе.', max_length=16, verbose_name='Статус'),
        ),
    ]
