# Generated by Django 5.2.12 on 2026-03-11 10:40

from django.db import migrations, models


def copy_role_from_m2m(apps, schema_editor):
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")
    through = User.roles.through
    role_by_id = {item.id: item.code for item in Role.objects.all()}

    for user in User.objects.all():
        role_code = "worker"
        role_id = (
            through.objects.filter(user_id=user.id).values_list("role_id", flat=True).first()
        )
        if role_id in role_by_id:
            role_code = role_by_id[role_id]
        user.role = role_code
        user.save(update_fields=["role"])


def reverse_copy_role_to_m2m(apps, schema_editor):
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")
    through = User.roles.through
    role_by_code = {item.code: item.id for item in Role.objects.all()}

    for user in User.objects.all():
        role_id = role_by_code.get(user.role)
        if role_id:
            through.objects.get_or_create(user_id=user.id, role_id=role_id)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_brigade_created_at_alter_brigade_foreman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[('administrator', 'Администратор'), ('director', 'Директор'), ('project_manager', 'Руководитель проекта'), ('foreman', 'Мастер (бригадир)'), ('worker', 'Монтажник'), ('support_manager', 'Менеджер по сопровождению'), ('designer', 'Проектировщик'), ('customer', 'Заказчик'), ('accountant', 'Бухгалтер')], db_index=True, default='worker', max_length=32, verbose_name='Роль'),
        ),
        migrations.RunPython(copy_role_from_m2m, reverse_copy_role_to_m2m),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
