# Generated by Django 5.2.12 on 2026-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(help_text='Уникальный ключ настройки, например: workday_start.', max_length=64, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(blank=True, help_text='Текущее значение настройки в строковом виде.', verbose_name='Значение'),
        ),
    ]
