# Generated by Django 5.2.12 on 2026-03-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_systemsetting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название базы расценок')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'База расценок',
                'verbose_name_plural': 'Базы расценок',
                'ordering': ('-updated_at',),
                'unique_together': {('title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=120, verbose_name='Раздел')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('unit', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расценка, руб.')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое содержание работ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pricelist', verbose_name='База расценок')),
            ],
            options={
                'verbose_name': 'Позиция расценки',
                'verbose_name_plural': 'Позиции расценок',
                'ordering': ('section', 'name'),
            },
        ),
    ]
